### ISSUE TITLE
"blog" links to current page

### ISSUE THREAD

**Issue by WilhelmBerggren** [callumrollo/callumrollo.github.io#4]
When visiting any page on the site, the "blog" link in the sidebar changes to the current page's URL (excluding any hash).

See preview in bottom left corner, taken while hovering over the "blog" link:

<img width="888" alt="image" src="https://github.com/user-attachments/assets/3859aa49-f638-4c63-981f-7821c0294277">

**Comment by callumrollo** [comment]
resolved in #5
